version: "3.3"

services:
  norfit_db:
    image: postgres:14.2-alpine
    container_name: norfit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: norfit_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes: 
      - norfit_volume:/var/lib/postgresql/data

  # norfit_backend:
  #   build: 
  #     context: '.'
  #   container_name: norfit_backend
  #   ports:
  #     - "3000:3000"
  #   expose:
  #     - "3000"
  #   depends_on: 
  #     test_db:
  #       condition: service_healthy

volumes:
  norfit_volume: