version: "1.0"

services:
  norfit_db:
    image: postgres:14.2-alpine
    container_name: norfit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: norfit_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes: 
      - norfit_db:/var/lib/postgresql/data
volumes:
  norfit_db: